### ISSUE TITLE
Create an action that `outputs` space-delimited issue numbers

### ISSUE THREAD

**Issue by smockle** [smockle/action-autolabel#9]
Follow-up to #5

From @smockle in https://github.com/smockle/action-autolabel/issues/5#issuecomment-901143765:
> …I’m planning another action (e.g. `smockle/action-issue-filter`) which would accumulate the issue numbers for issues with a specified label and provide them via `outputs`.

From @smockle in https://github.com/smockle/action-autolabel/issues/5#issuecomment-902124523:
> …I’ll build several single-purpose actions (e.g. a complementary `smockle/action-number-issues` or `smockle/action-filter-issues`, as [proposed above](https://github.com/smockle/action-autolabel/issues/5#issuecomment-901143765)), and workflows can compose them together.

### TODO

- [x] Debug missing `github` context, which is causing runs to fail: https://github.com/smockle/action-filter-issues/actions/runs/1187884066
- [x] Debug unexpected `output` (`{}` instead of `"1"`): https://github.com/smockle/action-filter-issues/runs/3499095716?check_suite_focus=true
- [x] Add pagination support (for repos with many issues)
- [x] (Low priority) Skip the [`Publish` workflow](https://github.com/smockle/action-filter-issues/actions/workflows/publish.yml) for Dependabot-initiated pushes to the `main` branch

**Comment by smockle** [comment]
[smockle/action-filter-issues](https://github.com/smockle/action-filter-issues) is very close to done. There are three known issues remaining:
- [ ] Debug missing `github` context, which is causing runs to fail: https://github.com/smockle/action-filter-issues/actions/runs/1187884066
- [ ] Add pagination support (for repos with many issues)
- [ ] (Low priority) Skip the [`Publish` workflow](https://github.com/smockle/action-filter-issues/actions/workflows/publish.yml) for Dependabot-initiated pushes to the `main` branch

**Comment by smockle** [comment]
> (Low priority) Skip the [`Publish` workflow](https://github.com/smockle/action-filter-issues/actions/workflows/publish.yml) for Dependabot-initiated pushes to the `main` branch

https://github.com/smockle/action-autolabel/commit/531a947da9282a34109cfa2f619bcc70ca08aa66 and https://github.com/smockle/action-filter-issues/commit/bca3969e938f9c25af76387a3c86daaf89c15a75 might resolve this (with a different approach).

**Comment by smockle** [comment]
From @smockle in https://github.com/smockle/action-autolabel/issues/9#issue-974952753:
> - [ ] Add pagination support (for repos with many issues)

Re: repos with many issues, I thought of a more efficient approach. Rather than retrieving all issues and then exclude/include filtering in JavaScript, instead retrieve issues for each label in `include_filters`, then intersect them, then filter the result with `exclude_filters`.

**Comment by smockle** [comment]
From @smockle in https://github.com/smockle/action-autolabel/issues/9#issue-974952753:
> - [x] Debug missing `github` context, which is causing runs to fail: https://github.com/smockle/action-filter-issues/actions/runs/1187884066

https://github.com/smockle/action-filter-issues/commit/7553338f12c0346d2ad1e27130abe6c26a7fdb64 resolves this. The issue is that—although `repository` in the [`github` context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) is a `string`—`repository` in the [webhook payload object](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-common-properties) is an `object`, and (TIL) `github.context.payload` is—despite what its name suggests—an instance of the latter, not the former. Applied an analogous fix in `smockle/action-autolabel` too: https://github.com/smockle/action-autolabel/commit/79b220c06836952e01fdbe1272ec0784c5c02809.

**Comment by smockle** [comment]
From @smockle in https://github.com/smockle/action-autolabel/issues/9#issue-974952753:
> * [x]  Debug unexpected `output` (`{}` instead of `"1"`): https://github.com/smockle/action-filter-issues/runs/3499095716?check_suite_focus=true

https://github.com/smockle/action-filter-issues/commit/25e94874e1c324d17e0aa4af212f859ed7e9f478 resolves this. This issue was a missing `await`, so the wrapped value was being sent via `outputs`. The [latest run](https://github.com/smockle/action-filter-issues/runs/3499312376?check_suite_focus=true) `echo`’d `"1"`, as expected.

**Comment by smockle** [comment]
From @smockle in https://github.com/smockle/action-autolabel/issues/9#issue-974952753:
> * [x]  Add pagination support (for repos with many issues)

Added in https://github.com/smockle/action-filter-issues/commit/7b107a262c4b3a25cee2ecfa54be5781442e2450!
